services:
  db:
        image: mysql:8.4
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - "3307:3306"
        healthcheck:
          test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -p\"$$MYSQL_ROOT_PASSWORD\"" ]
          interval: 5s
          timeout: 5s
          retries: 20
          start_period: 20s
        volumes:
          - mysql-data:/var/lib/mysql

  backend:
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
        environment:
            SERVER_PORT: 8080
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
            SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
            SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
            GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        depends_on:
          db:
            condition: service_healthy
        restart: unless-stopped

volumes:
  mysql-data:
